#!/bin/bash

#SBATCH -N 1
#SBATCH -n 4
#SBATCH --gpus 4
#SBATCH --time 60
#SBATCH --exclusive
#SBATCH -A fractale
#SBATCH -perl

. .venvs/scaffoldvenv-matrix/bin/activate

export LD_LIBRARY_PATH=/usr/lib64:$LD_LIBRARY_PATH

# Use Triton compiled channels-last groupnorm instead of PyTorch compiled contiguous groupnorm, which will incur an extra channels-last conversion.
# The Triton GN is optimized for AMD MI300A, but we have still noticed almost ~2x improved performance on H100.
export SCAFFOLD_GROUPNORM_TRITON=1

CONFIG_PATH="$(pwd)/ScaFFold/configs/benchmark_default.yml"

scaffold generate_fractals \
    -c "$CONFIG_PATH" \

# Uncomment if you want torch profiling
#export PROFILE_TORCH=ON

torchrun-hpc -N 1 -n 4 --gpus-per-proc 1 $(which scaffold) benchmark \
    -c "$CONFIG_PATH" \

#torchrun-hpc -N 2 -n 4 --gpus-per-proc 1 $(which scaffold) benchmark -c "$CONFIG_PATH"
